### ISSUE TITLE
Missing requirements.txt file

### ISSUE THREAD

**Issue by xsb** [ifosch/accloudtant#80]
I wanted to run accloudtant inside Docker using `FROM python:2.7-onbuild`.

This is the output of `docker build`:

```
# Executing 3 build triggers...
Step 1 : COPY requirements.txt /usr/src/app/
lstat requirements.txt: no such file or directory
```

More info on how _onbuild_ works
https://hub.docker.com/_/python/

**Comment by ifosch** [comment]
Certainly, adding a requirements.txt file is something pending since too long time.
Could you try to use `python:alpine` image and do `pip install accloudtant` on it, would be much easier.
Maybe we would provide some docker images, we just considered accloudtant to be in a too early development stage yet.
